from web3 import Web3
import json
from pycardano import Address as CardanoAddress
from pycardano.serialization import CBORSerializable
import cbor2

class Erc20TokenRemote:
    def __init__(self, node_url, token_home_addr, abi_path):
        self.w3 = Web3(Web3.HTTPProvider(node_url))
        with open(abi_path, 'r') as f:
            abi = json.load(f)
            if 'abi' in abi: abi = abi['abi']
        self.contract = self.w3.eth.contract(address=token_home_addr, abi=abi)

    def encode_plutus_data(self, target_cardano_addr, amount):
        """
        Encodes BeneficiaryData for the EVM send function.
        Matches Wanchain XPort Cardano bridge requirements (DemoMsgCodec).
        """
        try:
            addr = CardanoAddress.from_primitive(target_cardano_addr)
            payment_cred = addr.payment_part.to_primitive()
            stake_cred = addr.staking_part.to_primitive() if addr.staking_part else None

            from pycardano import VerificationKeyHash
            p_tag = 0 if isinstance(addr.payment_part, VerificationKeyHash) else 1

            # 1. Plutus Address structure: [ PaymentCredential, Option StakeCredential ]
            ada_address = cbor2.CBORTag(121, [
                cbor2.CBORTag(121 + p_tag, [payment_cred]),
                cbor2.CBORTag(121, [cbor2.CBORTag(121, [stake_cred])]) if stake_cred else cbor2.CBORTag(122, [])
            ])

            # 2. LocalAddress wrapper (Tag 122)
            # Match DemoMsgCodec: msgAddress -> msgAddressFields -> receiver -> adaAddress
            receiver = cbor2.CBORTag(121, [ada_address])
            msg_address_fields = cbor2.CBORTag(121, [receiver])
            msg_address = cbor2.CBORTag(122, [msg_address_fields])

            # 3. BeneficiaryData: [ address, amount ]
            beneficiary_data = cbor2.CBORTag(121, [msg_address, int(amount)])

            # 4. Final wrapper: [ beneficiary_data ]
            return cbor2.dumps([beneficiary_data])
        except Exception as e:
            # Fallback to foreign address (Tag 0) if not a valid Cardano address
            msg_address = cbor2.CBORTag(121, [target_cardano_addr.encode('utf-8')])
            beneficiary_data = cbor2.CBORTag(121, [msg_address, int(amount)])
            return cbor2.dumps(beneficiary_data)

    def send(self, private_key, plutus_data, gas_limit=300000):
        account = self.w3.eth.account.from_key(private_key)

        # In the demo, 'send' takes the plutusData generated by the user
        # plutusData contains target Cardano address and amount

        nonce = self.w3.eth.get_transaction_count(account.address)

        # Build transaction
        tx = self.contract.functions.send(plutus_data).build_transaction({
            'from': account.address,
            'nonce': nonce,
            'gas': gas_limit,
            'gasPrice': self.w3.eth.gas_price
        })

        signed_tx = self.w3.eth.account.sign_transaction(tx, private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed_tx.raw_transaction)

        return tx_hash.hex(), None
