from web3 import Web3
import json
from pycardano import Address as CardanoAddress
from pycardano.serialization import CBORSerializable

class Erc20TokenRemote:
    def __init__(self, node_url, token_home_addr, abi_path):
        self.w3 = Web3(Web3.HTTPProvider(node_url))
        with open(abi_path, 'r') as f:
            abi = json.load(f)
            if 'abi' in abi: abi = abi['abi']
        self.contract = self.w3.eth.contract(address=token_home_addr, abi=abi)

    def encode_plutus_data(self, target_cardano_addr, amount):
        # Match MeshSDK genBeneficiaryData logic
        # data BeneficiaryData = BeneficiaryData { receiver :: MsgAddress, amount :: Integer }
        # data MsgAddress = ForeignAddress BuiltinByteString | LocalAddress Address

        addr = CardanoAddress.from_primitive(target_cardano_addr)
        # LocalAddress is constructor 1
        # Payment credential is index 0 (VerificationKey) or 1 (Script)

        # Simplified reconstruction of PlutusData for Cardano Address
        # This is complex to do purely in Python without MeshSDK but we can approximate for the runner

        # Using a placeholder for now as full Plutus Address serialization is complex
        # In a real tool, we would use a library that handles Plutus Data encoding accurately
        return b"dummy"

    def send(self, private_key, plutus_data, gas_limit=300000):
        account = self.w3.eth.account.from_key(private_key)

        # In the demo, 'send' takes the plutusData generated by the user
        # plutusData contains target Cardano address and amount

        nonce = self.w3.eth.get_transaction_count(account.address)

        # Build transaction
        tx = self.contract.functions.send(plutus_data).build_transaction({
            'from': account.address,
            'nonce': nonce,
            'gas': gas_limit,
            'gasPrice': self.w3.eth.gas_price
        })

        signed_tx = self.w3.eth.account.sign_transaction(tx, private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed_tx.rawTransaction)

        return tx_hash.hex(), None
